// @flow

// ui
export const SET_UI_STATE = 'ui/SET_UI_STATE';
export const GENERATE_RANDOM_STRING = 'GENERATE_RANDOM_STRING';

// gallery
export const LOAD_IMAGES_REQUEST = 'LOAD_IMAGES_REQUEST';
export const START_CAROUSEL_REQUEST = 'START_CAROUSEL_REQUEST';
export const STOP_CAROUSEL_REQUEST = 'STOP_CAROUSEL_REQUEST';

// resources
export const FETCH_RESOURCES_REQUEST = 'FETCH_RESOURCES_REQUEST';
